# Project identification
sonar.projectKey=SonarQube-Jenkins-for-simple-express-app
sonar.projectName=SonarQube-Jenkins for simple-express-app
sonar.projectVersion=1.0

# Source code encoding and language
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.sources=.

# Optional: if using branches in SonarQube
# sonar.branch.name=feature/lab
